"""Add population_data to Simulation

Revision ID: 5df08c468584
Revises: 8b8a6099d451
Create Date: 2026-07-12 13:56:58.679723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df08c468584'
down_revision: Union[str, Sequence[str], None] = '8b8a6099d451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('population_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'population_data')
    # ### end Alembic commands ###
